operation:
    pattern:  /
    defaults: { _controller: "WrathOperationBundle:Operation:index" }

operation_show:
    pattern:  /{id}/show
    defaults: { _controller: "WrathOperationBundle:Operation:show" }

operation_new:
    pattern:  /new
    defaults: { _controller: "WrathOperationBundle:Operation:new" }

operation_create:
    pattern:  /create
    defaults: { _controller: "WrathOperationBundle:Operation:create" }
    requirements: { _method: post }

operation_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "WrathOperationBundle:Operation:edit" }

operation_update:
    pattern:  /{id}/update
    defaults: { _controller: "WrathOperationBundle:Operation:update" }
    requirements: { _method: post }

operation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "WrathOperationBundle:Operation:delete" }
    requirements: { _method: post }

operation_end:
    pattern: /{id}/end
    defaults: { _controller: "WrathOperationBundle:Operation:end" }

operation_confirm:
    pattern: /{id}/confirm
    defaults: { _controller: "WrathOperationBundle:Operation:confirm" }
    
operation_pay:
    pattern: /{id}/pay
    defaults: { _controller: "WrathOperationBundle:Operation:pay" }
    
operation_join:
    pattern: /{id}/join
    defaults: { _controller: "WrathOperationBundle:Operation:join" }
  
operation_leave:
    pattern: /{id}/leave
    defaults: { _controller: "WrathOperationBundle:Operation:leave" }