parameters:
#    wrath_content.example.class: Wrath\ContentBundle\Example

services:
#    wrath_content.example:
#        class: %wrath_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
